services:
  afl-libjpeg-main:
    image: fuzz-libjpeg-turbo
    # Use COMPOSE_PROJECT_NAME (or default "default") to build a unique container name.
    container_name: "${COMPOSE_PROJECT_NAME:-default}-afl-libjpeg"
    environment:
      - CORPUS_DIR=/corpus
      - OUTPUT_DIR=/afl-output
      - MINIMIZED_DIR=/corpus_min
      - FUZZER_ID=master
        #- AFL_MAP_SIZE=178990
        #- AFL_SKIP_CRASHES=1
    volumes:
      - ./corpus:/corpus:rw
        #- ./corpus_filtered:/corpus_filtered:rw 
      - ./corpus_min:/corpus_min
      - output-volume:/afl-output:rw
    tty: true
    stdin_open: true
    restart: "no"
  afl-secondary:
    image: fuzz-libjpeg-turbo
    environment:
      - CORPUS_DIR=/corpus
      - OUTPUT_DIR=/afl-output
    # Do not set FUZZER_ID for secondary containers.
    volumes:
      - ./corpus:/corpus:rw
      - output-volume:/afl-output:rw
    tty: true
    stdin_open: true
    restart: "no"
volumes:
  output-volume:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ${PWD}/afl-output-volume
