services:
  afl-libpng-main:
    image: fuzz-libpng
    # Use COMPOSE_PROJECT_NAME (or default "default") to build a unique container name.
    container_name: "${COMPOSE_PROJECT_NAME:-default}-afl-libpng"
    environment:
      CORPUS_DIR: /corpus
      OUTPUT_DIR: /afl-output
      FUZZER_BIN: /out/fuzz_target
      FUZZER_ID: master
    volumes:
      - ./corpus:/corpus:rw
      - output-volume:/afl-output:rw
    entrypoint: ["/entrypoint.sh"]
    tty: true
    stdin_open: true
    restart: "no"
volumes:
  output-volume: