services:
  # AFL++ with minimization
  afl-libxml2_xml-main:
    image: fuzz-libxml2_xml
    privileged: true
    container_name: "${COMPOSE_PROJECT_NAME:-default}-afl-libxml2_xml"
    environment:
      CORPUS_DIR: /corpus
      OUTPUT_DIR: /afl-output
      FUZZER_ID: master

      # Optional override:
      FUZZER_BIN: /out/xml
      STACK_FRAMES: 3
      SHOW_GDB: "false"
    volumes:
      - ./corpus:/corpus:rw
      - output-volume:/afl-output:rw
    entrypoint: ["/entrypoint.sh"]
    tty: true
    stdin_open: true
    restart: "no"
volumes:
  output-volume:
