services:
  # AFL++ with minimization
  afl-libass-2-main:
    image: fuzz-libass-2
    container_name: "${COMPOSE_PROJECT_NAME:-default}-afl-libass-2"
    environment:
      CORPUS_DIR: /corpus
      OUTPUT_DIR: /afl-output
      FUZZER_ID: master
    volumes:
      - ./corpus:/corpus:rw
      - output-volume:/afl-output:rw
    entrypoint: ["/entrypoint.sh"]
    tty: true
    stdin_open: true
    restart: "no"
volumes:
  output-volume: