services:
  # AFL++ with minimization
  afl-<application-name>-main:
    image: fuzz-<application-name>
    privileged: true
    container_name: "${COMPOSE_PROJECT_NAME:-default}-afl-<application-name>"
    environment:
      CORPUS_DIR: /corpus
      OUTPUT_DIR: /afl-output
      MINIMIZED_DIR: /corpus_min
      FUZZER_ID: master
      STACK_FRAMES: 3
      SHOW_GDB: "false"
    volumes:
      - ./corpus:/corpus:rw
      - output-volume:/afl-output:rw
      - minimized-corpus-volume:/corpus_min:rw
    entrypoint: ["/entrypoint.sh", "minimize"]
    tty: true
    stdin_open: true
    restart: "no"
  # AFL++ without minimization
  afl-<application-name>-unmin:
    image: fuzz-<application-name>
    privileged: true
    container_name: "${COMPOSE_PROJECT_NAME:-default}-afl-<application-name>-unmin"
    environment:
      CORPUS_DIR: /corpus
      OUTPUT_DIR: /afl-output
      FUZZER_ID: master
      STACK_FRAMES: 3
      SHOW_GDB: "false"
    volumes:
      - ./corpus:/corpus:rw
      - unmin-output-volume:/afl-output:rw
    entrypoint: ["/entrypoint.sh"]
    tty: true
    stdin_open: true
    restart: "no"
volumes:
  # AFL output for minimized AFL run
  output-volume:
  # AFL output for unminimized AFL run
  unmin-output-volume:
  # Minimized corpus for minimized AFL run
  minimized-corpus-volume:
